name: alkebuware_website
description: alkebuware.com web application
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: 0.1.5
  url_launcher: 5.4.7
  photo_view: 0.9.2
  string_validator: 0.1.4
  http: 0.12.1
  sentry: 3.0.1
  responsive_builder: 0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/menu.png
    - assets/images/vertical_logo.png
    - assets/images/close.png
    - assets/images/alosha-discover.png
    - assets/images/home-background.png
    - assets/images/alosha-profile.png
    - assets/images/boss-cuts-home.png
    - assets/images/tceshop-product-detail.png
    - assets/images/zakiyah-acosta.jpg
    - assets/images/josh-york.jpg
    - assets/images/app-development.png
    - assets/images/web-development.png
    - assets/images/ui-design.png
    - assets/images/close-dark-blue.png
    - assets/images/alosha-icon.png
    - assets/images/boss-cuts-icon.png
    - assets/images/companions-forever-icon.png
    - assets/images/tce-shop-icon.png
    - assets/images/alosha-home.png
    - assets/images/alosha-product-detail.png
    - assets/images/alosha-profile-artwork.png
    - assets/images/alosha-profile-activity.png
    - assets/images/alosha-share-questionnaire.png
    - assets/images/alosha-share-success.png
    - assets/images/alosha-sign-up.png
    - assets/images/boss-cuts-home.png
    - assets/images/boss-cuts-login.png
    - assets/images/boss-cuts-location.png
    - assets/images/boss-cuts-products.png
    - assets/images/boss-cuts-styles.png
    - assets/images/tceshop-product-detail.png
    - assets/images/tceshop-category.png
    - assets/images/tceshop-checkout-payment-method.png
    - assets/images/tceshop-checkout-shipping-method.png
    - assets/images/tceshop-dashboard-home.png
    - assets/images/tceshop-dashboard-product-detail.png
    - assets/images/tceshop-product-detail-desktop.png
    - assets/images/tceshop-search-desktop.png
    - assets/images/hand-shake.png
    - assets/images/inquiry.png
    - assets/images/send.png
    - assets/images/send-large-blue.png
    - assets/images/haqq-app-home.png
    - assets/images/haqq-app-loyalty.png
    - assets/images/haqq-app-search.png
    - assets/images/haqq-loyalty-analytics.png
    - assets/images/haqq-loyalty-customer.png
    - assets/images/haqq-loyalty-home.png
    - assets/images/angulardart-badge.png
    - assets/images/angulardart-badge.png
    - assets/images/aqueduct-badge.png
    - assets/images/css3-badge.png
    - assets/images/dart-badge.png
    - assets/images/firebase-badge.png
    - assets/images/flutter-badge.png
    - assets/images/gcp-badge.png
    - assets/images/html5-badge.png
    - assets/images/js-badge.png
    - assets/images/postgres-badge.png
    - assets/images/download.png
    - assets/images/linkedin.png
    - assets/images/ui-design2.png
    - assets/images/consulting.png
    - assets/images/development.png
    - assets/images/professional.png
    - assets/images/full-logo.png

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
