name: alkebuware_website
description: alkebuware.com web application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.4
  photo_view: ^0.14.0
  string_validator: ^1.0.2
  http: ^1.2.0
  sentry: ^7.15.0
  responsive_builder: ^0.7.0
  transparent_image: ^2.0.1
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
